'use strict';

/**
 * Observer and Reflector prompts adapted from Mastra's observational memory system.
 * See: https://mastra.ai/research/observational-memory
 *
 * Key adaptations for Claude Code:
 * - Output is appended to .claude/observations.md (not XML)
 * - Uses [P1]/[P2]/[P3] text priorities (not emoji, for cross-platform stderr)
 * - Claude writes from its own session context (not a separate agent)
 * - Includes current-task and suggested-next for session continuity
 */

var OBSERVER_PROMPT = [
  '<observation-request>',
  'You are performing an observation cycle. Your observations will be the ONLY information',
  'available about past interactions in future sessions. Extract observations from your',
  'current session context and write them to the appropriate observation files.',
  '',
  '=== WHAT TO EXTRACT ===',
  '',
  'CRITICAL: DISTINGUISH ASSERTIONS FROM QUESTIONS',
  '- User TELLS you something -> [P1] "User stated [fact]" (authoritative)',
  '- User ASKS something -> [P2] "User asked [question]"',
  '- User assertions are the source of truth. A later question does not invalidate a prior assertion.',
  '',
  'STATE CHANGES:',
  'When information updates or supersedes previous info, make it explicit:',
  '- GOOD: "User will use new method (replacing old approach)"',
  '- BAD: "User plans to use the new method"',
  '',
  'TEMPORAL ANCHORING (three-date model):',
  'Each observation carries up to three dates:',
  '1. OBSERVATION DATE: When the observation was created (the Date: header) - ALWAYS present',
  '2. REFERENCED DATE: A specific date mentioned in the content - include when stated',
  '3. RELATIVE DATE: Computed actual date from relative expressions - include when computable',
  '',
  'Format: (HH:MM) [observation]. {ref: DATE} or {rel: DATE from "expression"}',
  '- Explicit date: (14:30) Deadline is March 15th for the API launch. {ref: 2026-03-15}',
  '- Relative expression: (14:30) User will visit parents this weekend. {rel: Feb 15-16 from "this weekend"}',
  '- No date reference: (14:30) User prefers TypeScript with strict mode.',
  '- Do NOT compute dates for vague terms like "recently", "soon", "lately"',
  '- Split multi-event statements into separate observation lines, each with its own dates',
  '',
  'DETAILS TO ALWAYS PRESERVE:',
  '- Names, handles, identifiers (@username, file paths, package names)',
  '- Numbers, counts, measurements (4 items, 20% improvement, 2.8GB)',
  '- Sequences, orderings, version numbers',
  '- Locations, distinguishing attributes (near X, based in Y, specializes in Z)',
  '- Exact phrasing when unusual (quote their specific terminology)',
  '- Code snippets, commands, or configurations being discussed',
  '- Architecture decisions and their rationale',
  '- Error messages and their resolutions',
  '',
  'WHEN ASSISTANT PROVIDES LISTS/RECOMMENDATIONS:',
  'Capture what distinguishes each item, not just "recommended 5 things":',
  '- GOOD: "Recommended: Library A (lightweight), Library B (full-featured), Library C (best DX)"',
  '- BAD: "Recommended some libraries"',
  '',
  'CONVERSATION CONTEXT TO CAPTURE:',
  '- What the user is working on and why',
  '- Project decisions, architecture choices, trade-offs discussed',
  '- User preferences (tools, style, approach)',
  '- What worked and what did not',
  '- Requirements and constraints mentioned',
  '- Tool/command results that informed decisions',
  '- Specific file paths, line numbers, function names relevant to ongoing work',
  '',
  '=== TOOL EVENT LOG ===',
  '',
  'A log of significant tool uses may exist at .claude/.tool-events.json.',
  'Reference it for what was done this session (files written/edited, tests run, tasks managed).',
  'Summarize tool activity in observations rather than listing each event.',
  '',
  '=== PROJECT VS GLOBAL OBSERVATIONS ===',
  '',
  'There are two observation scopes. Write each observation to the correct file:',
  '',
  'PROJECT observations (.claude/observations.md):',
  '- Codebase facts, architecture decisions, conventions',
  '- Project-specific technical details, dependencies, config',
  '- Bug fixes, feature implementations, refactors in this project',
  '- Most observations belong here',
  '',
  'GLOBAL observations (~/.claude/observational-memory/observations-global.md):',
  '- User preferences (coding style, tool preferences, communication style)',
  '- Cross-project workflows and habits',
  '- Tools, frameworks, and services the user uses across projects',
  '- Personal context (timezone, role, team) if shared',
  '',
  'When uncertain, default to PROJECT (more common case).',
  '',
  '=== COMMITTED VS LOCAL OBSERVATIONS ===',
  '',
  'Project observations are split into two files:',
  '',
  'COMMITTED (.claude/observations.md): shared, safe to commit to git',
  '- Architecture decisions, project conventions, tech stack',
  '- Completed feature descriptions, bug fix root causes',
  '- Configuration notes, API contracts',
  '',
  'LOCAL (.claude/observations.local.md): session-specific, gitignored',
  '- "Current Task" and "Suggested Next" lines (ALWAYS local)',
  '- Work in progress, debugging context, partial implementations',
  '- Temporary state ("blocked on...", "waiting for...")',
  '',
  'When uncertain, default to LOCAL (safer — can be moved to committed later).',
  '',
  '=== OUTPUT FORMAT ===',
  '',
  'Append to the appropriate file(s) using this EXACT format:',
  '',
  'Date: YYYY-MM-DD',
  '- [P1] (HH:MM) Important facts, decisions, or user assertions',
  '  - [P2] (HH:MM) Supporting project details, tool results',
  '  - [P3] (HH:MM) Minor details, uncertain observations',
  '',
  'Examples with temporal anchoring:',
  '- [P1] (14:30) API launch deadline is March 15th. {ref: 2026-03-15}',
  '- [P1] (14:35) Sprint review moved to next Tuesday. {rel: 2026-02-18 from "next Tuesday"}',
  '- [P2] (14:33) Debugging auth issue in src/auth.ts',
  '  - ran git status, found 3 modified files',
  '  - viewed auth.ts:45-60, found missing null check',
  '  - applied fix, tests now pass',
  '',
  'Priority levels:',
  '- [P1] = critical: explicit user facts, preferences, decisions, goals achieved',
  '- [P2] = moderate: project details, tool results, technical context',
  '- [P3] = informational: minor details, uncertain observations',
  '',
  'After the observations, add these two sections to .claude/observations.local.md:',
  '',
  'Current Task: [What you are currently working on. If multiple tasks, list primary and secondary.',
  'If waiting for user input, say so.]',
  '',
  'Suggested Next: [Hint for continuing in the next session. Be specific:',
  '"Continue implementing the auth middleware in src/middleware/auth.ts"',
  'NOT "Continue working on the project"]',
  '',
  '=== PLAN PERSISTENCE ===',
  '',
  'If there is an active implementation plan in context (numbered steps, task list, or phased approach):',
  '- Detect the current branch: run `git branch --show-current`',
  '- Write or update .claude/plans/<branch-name>.md with the full plan',
  '  - Create the .claude/plans/ directory if it does not exist',
  '  - Example: on branch "feature/auth", write to .claude/plans/feature/auth.md',
  '- Mark completed steps with [x] and pending steps with [ ]',
  '- Include enough detail that someone reading only the plan file can continue the work',
  '- In observations, reference the plan: "[P1] Active plan in .claude/plans/<branch>.md — on step N of M"',
  '',
  '=== RULES ===',
  '',
  '- Append to the existing file(s) (do not overwrite prior observations)',
  '- Aim for 5-15 observation lines per session chunk',
  '- Use terse language to save tokens. Sentences should be dense.',
  '- Do not repeat observations already in the file',
  '- If the user provides detailed messages or code, capture the important details',
  '- Observe WHAT happened and WHAT it means, not HOW well it was done',
  '- After writing, display this notification to the user on its own line:',
  '  "Observations updated. You can /clear to start fresh — observations will be re-injected automatically."',
  '- Then stop. No other commentary.',
  '</observation-request>'
].join('\n');

var REFLECTOR_PROMPT = [
  '<reflection-request>',
  'You are performing a reflection cycle. The observation files have grown large and need consolidation.',
  'Read BOTH files, then REWRITE each with consolidated observations.',
  '',
  'Files to consolidate:',
  '- .claude/observations.md (committed: project facts, architecture, conventions)',
  '- .claude/observations.local.md (local: session state, WIP, Current Task/Suggested Next)',
  '',
  'You are reflecting on observations that were created with these priorities:',
  '- [P1] = critical: user facts, preferences, decisions, goals',
  '- [P2] = moderate: project details, tool results, context',
  '- [P3] = informational: minor details, uncertain observations',
  '',
  'CRITICAL: Your reflection is THE ENTIRETY of the assistant\'s memory. Any information you',
  'do not include will be immediately and permanently forgotten. Your output must assume the',
  'assistant knows nothing else.',
  '',
  '=== CONSOLIDATION RULES ===',
  '',
  'When consolidating observations:',
  '- Condense OLDER observations more aggressively, retain more detail for RECENT ones',
  '- Combine related items (e.g., "ran view tool 5 times on file X" instead of listing each)',
  '- Drop redundant or superseded context (if user changed from A to B, drop references to A)',
  '- Preserve dates/times and {ref:}/{rel:} temporal annotations (critical for temporal reasoning)',
  '- Maintain the event-log structure (do NOT summarize into paragraphs)',
  '- Keep the [P1]/[P2]/[P3] priority levels',
  '',
  'USER ASSERTIONS TAKE PRECEDENCE:',
  '- "User stated: X" = authoritative (user told us about themselves)',
  '- "User asked: X" = question (user seeking information)',
  '- If both exist for the same topic, keep the assertion - the question does not invalidate it',
  '',
  'STATE CHANGES:',
  '- When a newer observation supersedes an older one, keep only the newer state',
  '- Make supersession explicit: "User switched to B (previously used A)"',
  '',
  'WHAT TO PRESERVE (never drop):',
  '- User preferences and stated facts [P1]',
  '- Architecture decisions and their rationale',
  '- Active task context and progress',
  '- Names, numbers, paths, and specific identifiers',
  '',
  'WHAT TO CONDENSE OR DROP:',
  '- Completed tasks with no ongoing relevance',
  '- Superseded decisions or outdated context',
  '- Repeated observations that say the same thing',
  '- Low-priority [P3] items from old dates',
  '- Detailed tool call sequences (condense to outcome)',
  '',
  '=== OUTPUT FORMAT ===',
  '',
  'Rewrite EACH file separately (replacing all content):',
  '',
  '.claude/observations.md (committed):',
  'Date: YYYY-MM-DD',
  '- [P1] (HH:MM) project fact or architecture decision',
  '  - [P2] (HH:MM) supporting detail',
  '',
  '.claude/observations.local.md (local):',
  'Date: YYYY-MM-DD',
  '- [P1] (HH:MM) session state or WIP note',
  '',
  'End the LOCAL file with:',
  'Current Task: [updated current task]',
  'Suggested Next: [updated suggestion for next session]',
  '',
  '=== RULES ===',
  '',
  '- Read both files first, then REWRITE each (replace all content)',
  '- The rewritten files should be significantly smaller than the originals',
  '- Do not lose any [P1] information - these are critical',
  '- "Current Task" and "Suggested Next" ALWAYS go in the local file',
  '- After writing, stop immediately with no further commentary',
  '</reflection-request>'
].join('\n');

module.exports = {
  OBSERVER_PROMPT: OBSERVER_PROMPT,
  REFLECTOR_PROMPT: REFLECTOR_PROMPT
};
